version: '3.1'

services:
  
  db:
    image: postgres
    container_name: postgres-curso
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer-curso
    restart: always
    ports:
      - 8080:8080

volumes:
  dbdata: