version: '3.1'

services:
  
  db:
    image: postgres
    container_name: postgres-curso
    ports:
      - 5434:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
    volumes:
      - dbdata:/var/lib/postgresql/data

  pg:
    image: dpage/pgadmin4
    container_name: pgadmin-curso
    restart: always
    ports:
      - 9090:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456

volumes:
  dbdata: